services:
  py-awesome-template:
    container_name: py-awesome-template
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    ports:
      # Change on the .env file on the root of the project
      - ${APP_PORT}:8000
    volumes:
      - ../:/home/app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
