name: "Continuos Integration - Workflow"
on:
  push:
    branches:
      # Here you can specify which branches you want to run the workflow
      - "main"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_NAME: ${{github.event.repository.name}}

jobs:
  code-styles-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Check code - Flake8
        run: uv run flake8 .;

      - name: Check code - Pylint
        run: uv run pylint app/ --disable=all --enable=e,f;

      - name: Check code - Isort
        run: uv run isort --check-only ./app

      - name: Test Coverage with Pytest
        run: ENV='test' uv run pytest --cov-config=.coveragerc --cov-report=term-missing --doctest-modules --cov=. app/

